hydra:
  run:
    dir: "." # Directory where the task is executed

# Gmail API credentials configuration
credentials_path: "./credentials.json"  # Path to the credentials file for Gmail API
token_path: "./token.json"              # Path to the token file for Gmail API

# Email settings for sending the newsletter
email:
  recipients:  # List of recipient email addresses
    - "lowrenhwa88@gmail.com"
  sender: "lowrenhwa88@gmail.com"            # Authorized sender email address
  subject: "Good Morning Newsletter"         # Email subject line
  format: html                         # Format of the email content: html or plain

# API settings for various functionalities in the newsletter
api:
  # Location settings for generating location-based content
  location: "Singapore"
  country_code: "SG"                         # Country code for geopy

  # Horoscope settings for including daily horoscopes
  horoscope_sign: "scorpio"

  # Text search settings (e.g., searching for cafes)
  text_search:
    text_query: "cafes"                      # Query for text search
    place_type: null                         # Type of place (e.g., "restaurant" or "museum")
    page_size: 10                            # Number of results to fetch
    min_rating: null                         # Minimum rating filter, e.g., 4.5
    price_levels:
      - "PRICE_LEVEL_INEXPENSIVE"
      - "PRICE_LEVEL_MODERATE"

  # Nearby search settings for locations such as restaurants and attractions
  nearby_search:
    random_location: true                    # Use a random location if true
    place_types:
      - "restaurant"
      - "tourist_attraction"
      - "art_gallery"                        # List of categories to include
    coordinates: [1.3521, 103.8198]          # Default coordinates: center of Singapore
    search_radius: 1000                      # Search radius in meters
    page_size: 10                            # Number of nearby results to fetch

# ArXiv settings to include research papers in the newsletter
arxiv:
  query: "Computer Vision"                   # Search query for arXiv
  max_results: 100                           # Maximum number of results to fetch
  random_k: 3                                # Number of random papers to include in the email 
                                             # (should be less than or equal to max_results)
  download_papers: true                      # Flag to indicate whether to download the papers
  storage_type: local                        # Storage option: "local" or "s3"
  storage_dir: "data/arvix_papers"           # Base path for local storage of papers

# S3 settings (used if storage_type is set to s3)
s3_config:
  bucket: "your-bucket-name"                 # Name of the S3 bucket
  region: "us-east-1"                        # AWS region where the bucket is located
  access_key_id: "YOUR_ACCESS_KEY"           # AWS access key ID for S3
  secret_access_key: "YOUR_SECRET_KEY"       # AWS secret access key for S3
  base_path: "papers"                        # Key prefix/path inside the bucket
