# Configuration for the good morning newsletter
hydra:
  run:
    dir: "." 

# Credentials for Gmail API
credentials_path: "./keys/credentials.json" # Path to the credentials file for Gmail API
token_path: "./keys/token.json"             # Path to the token file for Gmail API

# Email settings
email:
  recipients: # Email addresses of recipients
  - "lowrenhwa88+1@gmail.com" 
  - "lowrenhwa88+2@gmail.com"
  sender: "lowrenhwa88@gmail.com" # The authorized sender email address
  subject: "Good Morning Newsletter" # Subject of the email   
  email_format: html # HTML or Text

# API settings
api:
  location: "Singapore"
  country_code: "SG"  # country code for geopy
  horoscope_sign: "scorpio"

  text_search:
    text_query: "cafes"
    place_type: null              # e.g., "restaurant", "museum"
    page_size: 10
    min_rating: null              # e.g., 4.5
    price_levels: ["PRICE_LEVEL_INEXPENSIVE", "PRICE_LEVEL_MODERATE"]        

  nearby_search:
    random_location: true             # If true, a random location will be used
    coordinates: [1.3521, 103.8198]  # Default: Singapore center
    place_types: ["restaurant", "tourist_attraction", "art_gallery"]     # Can be a list of categories
    search_radius: 1000            # in meters
    page_size: 10


# ArXiv settings
arxiv:
  query: "RAG LLM"  # Change this value to search for a different query
  max_results: 100              # Maximum number of results to fetch from arXiv
  random_k: 3                # Number of random papers to include in the email, this should be less than or equal to max_results
  download_papers: true  # Whether to download the papers
  storage_type: local  # Options: "local" or "s3"
  storage_dir: "data/arvix_papers"  # Base path for local storage

# S3 settings (if storage_type is s3)
s3_config:
  bucket: "your-bucket-name"
  region: "us-east-1"
  access_key_id: "YOUR_ACCESS_KEY"
  secret_access_key: "YOUR_SECRET_KEY"
  base_path: "papers"  # The key prefix inside the bucket
