---
version: 1
disable_existing_loggers: False
formatters:
  json:
    format: "%(asctime)s %(module)s %(message)s"  #"%(asctime)s %(process)d %(name)s %(levelname)s %(message)s"
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    datefmt: "%d-%m-%Y %H:%M" #datefmt: "%Y-%m-%dT%H:%M:%S%z"

  rich_formatter:
    format: "%(message)s"

handlers:
  console:
    class: rich.logging.RichHandler
    level: INFO
    formatter: rich_formatter
    rich_tracebacks: True
    markup: True

  debug_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: json
      filename: logs/debug.log
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8
      delay: True

  info_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: json
      filename: logs/info.log
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8
      delay: True

  error_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: ERROR
      formatter: json
      filename: logs/errors.log
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8
      delay: True

root:
  level: INFO
  handlers: [console, debug_file_handler, info_file_handler, error_file_handler]
