name: Workflow Status Notification

on:
  workflow_run:
    workflows: ["Send Daily Newsletter"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Log failure details
      run: |
        echo "📧 Newsletter workflow failed!"
        echo "Workflow: ${{ github.event.workflow_run.name }}"
        echo "Run ID: ${{ github.event.workflow_run.id }}"
        echo "Branch: ${{ github.event.workflow_run.head_branch }}"
        echo "Conclusion: ${{ github.event.workflow_run.conclusion }}"
        echo "URL: ${{ github.event.workflow_run.html_url }}"
        
        # You can add additional notification logic here
        # For example, send to Slack, Discord, or create an issue
        
    - name: Create issue on failure (optional)
      if: ${{ github.event.workflow_run.conclusion == 'failure' }}
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Newsletter workflow failed - ${new Date().toISOString().split('T')[0]}`,
            body: `
            ## 🚨 Newsletter Workflow Failure
            
            The daily newsletter workflow has failed.
            
            **Details:**
            - Workflow: ${{ github.event.workflow_run.name }}
            - Run ID: ${{ github.event.workflow_run.id }}
            - Branch: ${{ github.event.workflow_run.head_branch }}
            - Conclusion: ${{ github.event.workflow_run.conclusion }}
            - URL: ${{ github.event.workflow_run.html_url }}
            
            **Next Steps:**
            1. Check the workflow logs for error details
            2. Verify API keys and secrets are still valid
            3. Check if external APIs are responding
            4. Run the health check workflow manually
            
            **Auto-generated issue** - Please investigate and close when resolved.
            `,
            labels: ['bug', 'workflow-failure', 'auto-generated']
          })
